nome = input('Diga seu nome: ')
idade = input('Diga sua idade: ')
linguagem_favorita = input('Diga sua linguagem favorita: ')
emoji = input('Informe um emoji: ')

print('_' * 15)
print() 
print(f'👩‍💻 Crachá do Dev') 
print() 
print(f'Nome: {nome}') 
print(f'Idade: {idade}') 
print(f'Linguagem favorita: {linguagem_favorita}') 
print(f'Emoji: {emoji}') 
print('_' * 15)